name: Deploy K8s
on:
  push:
    branches:
      - main
env:
  SHA: $(git rev-parse HEAD)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Service Key
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"
          project_id: weekly-462609

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: weekly-cluster-1
          location: me-west1
      - name: Build
        run: |-
          docker build -t grady305/weekly-server:latest -t grady305/weekly-server:${{ env.SHA }} -f ./Dockerfile .
      - name: Push
        run: |-
          docker push grady305/weekly-server:latest
          docker push grady305/weekly-server:${{ env.SHA }}
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/api-deployment api=grady305/weekly-server:${{ env.SHA }}
