name: Deploy
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t grady305/weekly-server ./

      - run: docker push grady305/weekly-server

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: weekly-server
          environment_name: Weekly-server-env
          existing_bucket_name: elasticbeanstalk-us-east-1-786009993834
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
